version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-el
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: uk.gov.hmcts.java
    versions:
    - 0.12.7
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: uk.gov.hmcts.reform:sscs-common
    versions:
    - 4.1.44
    - 4.2.0
    - 4.2.1
    - 4.2.18
    - 4.2.20
    - 4.2.21
    - 4.2.24
    - 4.2.28
    - 4.2.29
    - 4.2.34
    - 4.2.35
    - 4.2.36
    - 4.2.5
  - dependency-name: org.elasticsearch:elasticsearch
    versions:
    - 7.11.0
